//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.21 at 11:37:40 PM GMT+08:00 
//


package GetJiraAPI;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the GetJiraAPI package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: GetJiraAPI
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestngResults }
     * 
     */
    public TestngResults createTestngResults() {
        return new TestngResults();
    }

    /**
     * Create an instance of {@link TestngResults.Suite }
     * 
     */
    public TestngResults.Suite createTestngResultsSuite() {
        return new TestngResults.Suite();
    }

    /**
     * Create an instance of {@link TestngResults.Suite.Test }
     * 
     */
    public TestngResults.Suite.Test createTestngResultsSuiteTest() {
        return new TestngResults.Suite.Test();
    }

    /**
     * Create an instance of {@link TestngResults.Suite.Test.Class }
     * 
     */
    public TestngResults.Suite.Test.Class createTestngResultsSuiteTestClass() {
        return new TestngResults.Suite.Test.Class();
    }

    /**
     * Create an instance of {@link TestngResults.Suite.Test.Class.TestMethod }
     * 
     */
    public TestngResults.Suite.Test.Class.TestMethod createTestngResultsSuiteTestClassTestMethod() {
        return new TestngResults.Suite.Test.Class.TestMethod();
    }

}
