//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.21 at 11:37:40 PM GMT+08:00 
//


package GetJiraAPI;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="suite">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="groups" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="test" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="class">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="test-method" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="is-config" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                                               &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                               &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                           &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="skipped" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="failed" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="ignored" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="passed" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reporterOutput",
    "suite"
})
@XmlRootElement(name = "testng-results")
public class TestngResults {

    @XmlElement(name = "reporter-output", required = true)
    protected String reporterOutput;
    @XmlElement(required = true)
    protected TestngResults.Suite suite;
    @XmlAttribute(name = "skipped")
    protected Byte skipped;
    @XmlAttribute(name = "failed")
    protected Byte failed;
    @XmlAttribute(name = "ignored")
    protected Byte ignored;
    @XmlAttribute(name = "total")
    protected Byte total;
    @XmlAttribute(name = "passed")
    protected Byte passed;

    /**
     * Gets the value of the reporterOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReporterOutput() {
        return reporterOutput;
    }

    /**
     * Sets the value of the reporterOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReporterOutput(String value) {
        this.reporterOutput = value;
    }

    /**
     * Gets the value of the suite property.
     * 
     * @return
     *     possible object is
     *     {@link TestngResults.Suite }
     *     
     */
    public TestngResults.Suite getSuite() {
        return suite;
    }

    /**
     * Sets the value of the suite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestngResults.Suite }
     *     
     */
    public void setSuite(TestngResults.Suite value) {
        this.suite = value;
    }

    /**
     * Gets the value of the skipped property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSkipped() {
        return skipped;
    }

    /**
     * Sets the value of the skipped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSkipped(Byte value) {
        this.skipped = value;
    }

    /**
     * Gets the value of the failed property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFailed() {
        return failed;
    }

    /**
     * Sets the value of the failed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFailed(Byte value) {
        this.failed = value;
    }

    /**
     * Gets the value of the ignored property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getIgnored() {
        return ignored;
    }

    /**
     * Sets the value of the ignored property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setIgnored(Byte value) {
        this.ignored = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setTotal(Byte value) {
        this.total = value;
    }

    /**
     * Gets the value of the passed property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPassed() {
        return passed;
    }

    /**
     * Sets the value of the passed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPassed(Byte value) {
        this.passed = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="groups" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="test" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="class">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="test-method" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="is-config" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                                     &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                                     &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
     *                 &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groups",
        "test"
    })
    public static class Suite {

        @XmlElement(required = true)
        protected String groups;
        protected List<TestngResults.Suite.Test> test;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "duration-ms")
        protected Short durationMs;
        @XmlAttribute(name = "started-at")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar startedAt;
        @XmlAttribute(name = "finished-at")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar finishedAt;

        /**
         * Gets the value of the groups property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroups() {
            return groups;
        }

        /**
         * Sets the value of the groups property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroups(String value) {
            this.groups = value;
        }

        /**
         * Gets the value of the test property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the test property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTest().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TestngResults.Suite.Test }
         * 
         * 
         */
        public List<TestngResults.Suite.Test> getTest() {
            if (test == null) {
                test = new ArrayList<TestngResults.Suite.Test>();
            }
            return this.test;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the durationMs property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getDurationMs() {
            return durationMs;
        }

        /**
         * Sets the value of the durationMs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setDurationMs(Short value) {
            this.durationMs = value;
        }

        /**
         * Gets the value of the startedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartedAt() {
            return startedAt;
        }

        /**
         * Sets the value of the startedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartedAt(XMLGregorianCalendar value) {
            this.startedAt = value;
        }

        /**
         * Gets the value of the finishedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFinishedAt() {
            return finishedAt;
        }

        /**
         * Sets the value of the finishedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFinishedAt(XMLGregorianCalendar value) {
            this.finishedAt = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="class">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="test-method" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="is-config" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
         *                           &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                           &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
         *       &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clazz"
        })
        public static class Test {

            @XmlElement(name = "class", required = true)
            protected TestngResults.Suite.Test.Class clazz;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "duration-ms")
            protected Short durationMs;
            @XmlAttribute(name = "started-at")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar startedAt;
            @XmlAttribute(name = "finished-at")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar finishedAt;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link TestngResults.Suite.Test.Class }
             *     
             */
            public TestngResults.Suite.Test.Class getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link TestngResults.Suite.Test.Class }
             *     
             */
            public void setClazz(TestngResults.Suite.Test.Class value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the durationMs property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getDurationMs() {
                return durationMs;
            }

            /**
             * Sets the value of the durationMs property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setDurationMs(Short value) {
                this.durationMs = value;
            }

            /**
             * Gets the value of the startedAt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getStartedAt() {
                return startedAt;
            }

            /**
             * Sets the value of the startedAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setStartedAt(XMLGregorianCalendar value) {
                this.startedAt = value;
            }

            /**
             * Gets the value of the finishedAt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFinishedAt() {
                return finishedAt;
            }

            /**
             * Sets the value of the finishedAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFinishedAt(XMLGregorianCalendar value) {
                this.finishedAt = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="test-method" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="is-config" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
             *                 &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *                 &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "testMethod"
            })
            public static class Class {

                @XmlElement(name = "test-method")
                protected List<TestngResults.Suite.Test.Class.TestMethod> testMethod;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the testMethod property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the testMethod property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTestMethod().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TestngResults.Suite.Test.Class.TestMethod }
                 * 
                 * 
                 */
                public List<TestngResults.Suite.Test.Class.TestMethod> getTestMethod() {
                    if (testMethod == null) {
                        testMethod = new ArrayList<TestngResults.Suite.Test.Class.TestMethod>();
                    }
                    return this.testMethod;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="is-config" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}short" />
                 *       &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
                 *       &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "reporterOutput"
                })
                public static class TestMethod {

                    @XmlElement(name = "reporter-output", required = true)
                    protected String reporterOutput;
                    @XmlAttribute(name = "status")
                    protected String status;
                    @XmlAttribute(name = "signature")
                    protected String signature;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "is-config")
                    protected String isConfig;
                    @XmlAttribute(name = "duration-ms")
                    protected Short durationMs;
                    @XmlAttribute(name = "started-at")
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar startedAt;
                    @XmlAttribute(name = "finished-at")
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar finishedAt;

                    /**
                     * Gets the value of the reporterOutput property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getReporterOutput() {
                        return reporterOutput;
                    }

                    /**
                     * Sets the value of the reporterOutput property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setReporterOutput(String value) {
                        this.reporterOutput = value;
                    }

                    /**
                     * Gets the value of the status property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getStatus() {
                        return status;
                    }

                    /**
                     * Sets the value of the status property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setStatus(String value) {
                        this.status = value;
                    }

                    /**
                     * Gets the value of the signature property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSignature() {
                        return signature;
                    }

                    /**
                     * Sets the value of the signature property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSignature(String value) {
                        this.signature = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the isConfig property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIsConfig() {
                        return isConfig;
                    }

                    /**
                     * Sets the value of the isConfig property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIsConfig(String value) {
                        this.isConfig = value;
                    }

                    /**
                     * Gets the value of the durationMs property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Short }
                     *     
                     */
                    public Short getDurationMs() {
                        return durationMs;
                    }

                    /**
                     * Sets the value of the durationMs property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Short }
                     *     
                     */
                    public void setDurationMs(Short value) {
                        this.durationMs = value;
                    }

                    /**
                     * Gets the value of the startedAt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getStartedAt() {
                        return startedAt;
                    }

                    /**
                     * Sets the value of the startedAt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setStartedAt(XMLGregorianCalendar value) {
                        this.startedAt = value;
                    }

                    /**
                     * Gets the value of the finishedAt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getFinishedAt() {
                        return finishedAt;
                    }

                    /**
                     * Sets the value of the finishedAt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setFinishedAt(XMLGregorianCalendar value) {
                        this.finishedAt = value;
                    }

                }

            }

        }

    }

}
